### PR TITLE
feat: let Sink callback do some init & terminate stuff

### PR DESCRIPTION
**Pull request by pouriya**

### CODE REVIEW

**Comment by ferd** [comment]
What is the intention here in terms of init and termination work? I'm a bit skittish about allowing this and having to carry state around. The other thing there is that it would make sense, if the rationale is good enough, to normalize on init/terminate callbacks, and to let carry state between one and the other.

On the other hand, since this hasn't been required in the 8 years this library existed, I'm curious to hear about the specific use case in play.

**Comment by pouriya** [comment]
IMO it's not **really** like init/terminate since it does not initialize a state as a return value in `start_stats` and does not accept its state thing in `stop_stats` but it let `Sink` know when it's initialized (and what it should do for it) and when it's terminated.
In my case, I'm creating an ETS table and put all `collect` values in it. Our monitoring agent (that is pull based and uses ReST API) collects latest values whenever it wants (every 5,10,30 seconds, etc).
Currently I have 2 options to keep this working:
1. For each `collect` I have to make sure that the ETS table exists (probably put `ets:insert` in `try...catch`, etc) and if it doesn't, I have to create it. I also have to read from table carefully (probably put `ets:lookup` in `try...catch` too and if I don't, I see process crash reports when the system is started and vmstat did not make its first `collect` call (to make me create table) but the monitoring agent keeps collecting (reading ETS ) data.
2. create the ETS table in another process (and make it public) before starting vmstat application.

So `start_stats` simply lets me create this ETS table and remove above checks (I preferred to go with solution 1).
I use vmstat in Ejabberd which is a plugin based system and in `stop_stats` I can simply add new hook callback to take the place and send a meaningful response describing that monitoring is disabled.

**Comment by ferd** [comment]
Hm. I get the concern given the existing project structure, but I'm not too sure I like the approach. For example, the terminate callback isn't guaranteed to be called at any point in time. 

I would probably be more keen to use the mechanism mentioned at step 1: run your metrics system that relies on ETS table on its own (whether it is a prometheus exporter or anything else), and register hooks in VMstats that publish to the metric system that you want.

Starting to manage lifecycles and the state of external mechanisms and states is something I'd rather not import in this library because it comes with a lot of concerns if you want to do it right.

**Comment by pouriya** [comment]
> For example, the terminate callback isn't guaranteed to be called at any point in time.  

What if we set `trap_exit` to `true`?

> I would probably be more keen to use the mechanism mentioned at step 1 ...  

The problem here is the checks for ETS table in `collect` callback and the checks for reading data (from web connection processes) when vmstat did not make its first call to `collect` (to create table).

**Comment by ferd** [comment]
Maybe vmstats isn't a good fit for this mechanism. It already internally tracks things like the scheduler, gc, or io statistics are to then be output without their historical values, only as timed-based increments. The callbacks just output the data to a place that should already exist or be created live, whether it's a UDP socket or anything like that.

I don't think it's a good idea to start supporting all these extensions in terms of usage patterns. Even the initial PR to support more sink types was not something I felt was a great idea. VMstats lived this long because it is dead simple and does only one thing and requires nearly no maintenance from me (or anyone). Its limitations are a strength, and it does imply that someone else handles the extra complexity elsewhere.

I would rather see it no longer used because it is not useful to its users than having to maintain an ever growing feature set to see it gain in usage I do not plan on personally maintaining.

At this point, I would recommend a fork maintained independently (I don't necessarily care for it to be renamed or not) because the project is headed in a direction I don't personally want to sign up for in terms of stewardship.

**Comment by pouriya** [comment]
I see. Thank you.

**Pull request closed without merging**
