### PR TITLE
Add support for OTP 21

### LINKED ISSUE #20: Possible bug getting error_logger stats on OTP 21
Hi, I was testing out OTP 21.0 and it seems like the logger changes they made are causing an error in vmstats_server:
```
** (ArgumentError) argument error
    :erlang.process_info(:undefined, :message_queue_len)
    (vmstats) /home/cbrodt/Projects/traitify/profile-svc/profile_service/deps/vmstats/src/vmstats_server.erl:98: :vmstats_server.handle_info/2
````

The above is from an Elixir project, but I don't think that should make a difference here. I got the error on both vmstats 2.2 and 2.3. The above message is from running with 2.3.

### PR DESCRIPTION
**Pull request by hauleth**
This checks if `error_logger` is running and only if send metrics.

Close #20

### CODE REVIEW

**Comment by ferd** [comment]
Thanks for the contribution!

**Comment by ferd** [comment]
Agh, I'm getting major test failures on OTP-19. Will investigate a bit

**Comment by hauleth** [comment]
@ferd installing OTP-19 to check what is the problem

**Comment by ferd** [comment]
It's okay I cleared it. I think it was due to atom_count not being supported back then, and I assume they were related to your tests.

**Pull request merged**
